# Configuration for pyLINEAR (Oct. 30, 2019)
# Configuration file for Roman Space Telescope slitless spectroscopy simulations

# First define the absolute path to this file
conffile: &CONFFILE /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/roman_grism_sim_config.yml

# CPU params
cpu: &CPU
  ncpu: 4                             # number of processors to use
  verbose: true

# Calibration params
calib: &CALIB
  h5conf: wfirst_wfi_wfi_beams.h5           # HDF5 file for beam info
  h5flat: null                           # HDF5 file for flat field
  h5siaf: wfirst_wfi_wfi_detector.h5        # HDF5 file for detectors

# H5 table params
tables: &TABLES
  path: /Users/baj/Documents/roman_slitless_sims_results/TABLES2/                         # relative path for the tables
  remake: true                           # force to remake the tables
  gzip: true                             # gzip the resulting data
  nsub: 5                                # num intervals for trap. integrate
  cpu: *CPU                              # import CPU settings
  
# Source params
sources:
  segmap: /Users/baj/Documents/roman_direct_sims/K_akari_rotate_subset/akari_match_Y106_11_1_segmap.fits                 # segmentation map for sources
  obslst: /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/obs.lst                        # file describing the bands
  detindex: 0                            # detection index in obslst
  maglim: 19.                            # magnitude limit of sources
  minpix: 5                              # minimum number of pixels
  filtsig: 0                             # sigma of Gaussian filter
  eroderad: 0                            # num of pix to remove on outer edge
  binfact: 0                             # num of pix to block average
  
# Params for simulation, extraction, and cutout modules
modules:
  simulation:
    perform: true                       # flag to run the simulation
    beam: A                              # beams to simulate
    grism: G141                          # which grism to simulate
    imgtype: wcs                         # where WCS comes from: wcs or img
    gzip: true                           # gzip the outputs
    imglst: /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/wcs.lst                      # list of WCS properties
    sedlst: /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/sed.lst                      # list of SEDs
    noise:                               # the noise module
      perform: false                     # flag to perform noise calculation
      exptime: 700.                      # effective exposure time
      skyrate: 0.3                       # background rate in e/s
    cpu: *CPU                            # import CPU settings
    calib: *CALIB                        # import calibration settings
    tables: *TABLES                      # import Tables settings

  extraction:
    perform: false                        # flag to perform the extraction
    mode: golden                         # type of extraction
    group: True                          # flag to group objects
    logdamp: [-5.,0.,0.1]                # damping values (depending on mode)
    outroot: romansim                        # rootname of output products
    imglst: /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/flt.lst                      # input list of FLTs to extract
    beam: A                              # beam(s) to extract
    mask: null                           # beam(s) to mask
    dqamask: 3583                        # bitmask for DQA (can also be binary
    lamb0: null                          # starting wavelength in A (optional)
    lamb1: null                          # ending wavelength in A (optional)
    dlamb: null                          # sampling wavelength in A (optional)
    initialize: 'broadband'              # how to initialize the extraction
    lsqr:
      atol: 1e-10                        # see scipy documentation
      btol: 1e-10                        # see scipy documentation
      conlim: 1e10                       # see scipy documentation
      maxiter: 1e5                       # see scipy documentation
      show: False                        # see scipy documentation
    cpu: *CPU                            # import CPU settings
    calib: *CALIB                        # import calibration settings
    tables: *TABLES                      # import table settings
    conffile: *CONFFILE                  # import config file path
    mcmcunc:
      perform: false                     # flag to do the MCMC uncertainties
      nwalkers: 100                      # num of walkers (see emcee dox)
      nstep: 100                         # num of steps/walker (see emcee dox)
      burn: 0.2                          # fraction to burn (see emcee dox)
      cpu: *CPU                          # import CPU settings
    residuals:
      perform: true                      # flag to compute residuals
      gzip: false                        # flag to gzip output file
          
  cutout:
    perform: false                       # flag to perform the cutouts
    beam: A                              # which beams to cutout
    imglst: /Users/baj/Documents/GitHub/roman-slitless/pyLINEARSN/flt.lst                      # the observed images to cutout
    padding: [0,2]                       # padding to the cutouts [x,y]
    cpu: *CPU                            # import CPU settings
    calib: *CALIB                        # import calibration settings
    tables: *TABLES                      # import table settings

