---
# Define constants
Lsol: 3.826e33  # erg/s
sn_scalefac: 1.734e40  # Check sn_scaling.py in roman-slitless

# survey pointing related
pointing: 0
detector: 1
disp_elem: 'P127'
ra_cen:   '71.9150429'  # needs to be a string  # look this up from dir img header in ds9
dec_cen: '-53.8258429'  # needs to be a string  # look this up from dir img header in ds9

# Direct image related
img:
  img_zp: 31.7956
  wfc3_f105w_zp: 26.264

  back_scale: 0.001  # standard deviation for background to be added.

  # Other img params
  basename: '5deg_'
  filt: 'Y106_'

# SNe insertion related
insert:
  lowmag:  19.0 # brightest mag SN to be inserted
  highmag: 31.0 # faintest mag SN to be inserted
  numlow:  10 #750  # min number of SNe to be inserted
  numhigh: 15 #800  # max number of SNe to be inserted
  ref_mag: 15.9180
  ref_counts: 13753.24  # read in mag and counts from SExtractor catalog on dir img
  ref_segid: 630
  ref_size: 50  # same as the size of the cutout stamp  # cutout is 100x100; need half that here

# pylinear config
pylin:
  beam: '+1'
  maglim: 32      # Faintest mag to be simulated/extracted
  dark: 0.01      # e/s/pix
  readnoise: 15   # electrons per read
  sky: 1.1        # e/s/pix; zodi + thermal + MW
  npix: 16777216  # 4096 * 4096

# Runtime config
verbose: False